# Generated by Django 4.2.2 on 2023-08-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(choices=[('Admin', 'Admin'), ('User', 'User')], max_length=10),
        ),
    ]
