# Generated by Django 4.2.2 on 2023-08-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='iimage',
        ),
    ]
