# Generated by Django 4.2.2 on 2023-08-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_image_profile_iimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='iimage',
            new_name='image',
        ),
    ]
