from django.contrib import admin
from . models import *

admin.site.register(Sex)
admin.site.register(Ratings)
admin.site.register(Role)
admin.site.register(AcademicProgram)
admin.site.register(Menu)
admin.site.register(Access)
admin.site.register(Contact)
admin.site.register(Department)
admin.site.register(Expired)
admin.site.register(FormReg)
admin.site.register(Level)
admin.site.register(Major)
admin.site.register(Married)
admin.site.register(Payment)
admin.site.register(Relationship)
admin.site.register(Subscribe)
admin.site.register(TuitionFee)
admin.site.register(Status)
admin.site.register(Subject)
admin.site.register(Shift)
# admin.site.register(Register)