# Generated by Django 4.2.2 on 2023-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
