# Generated by Django 4.2.2 on 2023-08-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_contact_link_alter_contact_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='link',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='text',
        ),
    ]
