# Generated by Django 4.2.2 on 2023-08-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_contact_link_contact_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formreg',
            name='form',
            field=models.BooleanField(default=True),
        ),
    ]
