# Generated by Django 4.2.2 on 2023-08-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_formreg_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='link2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
