# Generated by Django 4.2.2 on 2023-08-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_contact_link2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionfee',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
