# Generated by Django 4.2.2 on 2023-08-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_remove_subject_title_subject_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='major',
        ),
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.major'),
            preserve_default=False,
        ),
    ]
