# Generated by Django 4.2.2 on 2023-08-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_remove_subject_major_subject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(limit_choices_to={'department__level': models.F('level')}, on_delete=django.db.models.deletion.CASCADE, to='index.level'),
        ),
    ]
