# Generated by Django 4.2.5 on 2023-09-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_subject_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Decided_By',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='Reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
