# Generated by Django 4.2.5 on 2023-09-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_register_decided_by_alter_register_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Decided_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
